<?php
 include_once('includes/header.php');
?>


<div class="hb-bannerCont">
	<div class="hb-bannerImgCont">
		<div class="hb-bannerImg">
			<picture>
			     <source media="(max-width: 768px)" srcset="images/banners/ppp_mbanner.png">
			      <img  src="images/banners/ppp_banner.png" alt="Harbour1 Cloud Backup as a Service Banner" style="width:100%">
      		</picture>
		</div>		
	</div>
</div>	


<section id="hb-ptnersCont">
	<div class="container">
		<div class="hb-patAdv">
			<div class="hb-patnerLeft">
				<h1>GTM Advantage</h1>
				<p>The Pi Partner Program gives you a new prospect of growth along with the ever growing data center leader in the Indian industry.</p>
				<p>The data pool generated by today’s enterprises has hiked the demand for data center and cloud services. The exponential drift in adoption and the need for intelligent data extraction & application call for smart and agile data centers which can scale to specific requirements.</p>
				<p>We continue to invest in the right technologies & infrastructure for our partners to leverage and expand their horizon, add that zing to their positioning and remain industry leaders in their own space.</p>
			</div>
			<div class="hb-patnerRight">
				<p>
					<img src="images/123.png">
				</p>
			</div>
		</div>
	</div>
</section>

<div class="hb-ourPartners">
	<div class="container">
		<div class="hb-ourCint">
			<h2 class="text-center">Our Partner Tracks</h2>
			<p class="text-center">Our partners bring in unique capabilities in terms of their industry reach and holistic nature of business. Cognizing this, Pi Partner Program offers varied partner tracks for you to choose your best fit.</p>
			<ul class="list-inline hb-ourListCont">
				<li>
					<span>
						<img src="images/partners/1_ico.png">
					</span>
					<p>Technology Alliances</p>
				</li>
				<li>
					<span>
						<img src="images/partners/2_ico.png">
					</span>
					<p>System Integrators</p>
				</li>
				<li>
					<span>
						<img src="images/partners/3_ico.png">
					</span>
					<p>Resellers</p>
				</li>
				<li>
					<span>
						<img src="images/partners/4_ico.png">
					</span>
					<p>ISVs</p>
				</li>
				<li>
					<span>
						<img src="images/partners/5_ico.png">
					</span>
					<p>Managed Service Providers</p>
				</li>
				<li>
					<span>
						<img src="images/partners/6_ico.png">
					</span>
					<p>OEM Partnerships</p>
				</li>
				<li>
					<span>
						<img src="images/partners/7_ico.png">
					</span>
					<p>Consulting Partners</p>
				</li>

			</ul>
		</div>
	</div>
</div>


<section>
	<div class="container">
		<div class="hb-ourCintInfo">
			<h2 class="text-center">Tech Advantage</h2>
			<p>Being a Smart and Software Defined Strategic Data Center (SDSDC) organisation, we provide you an incredible opportunity, as a partner, to deliver the best to your customer’s ever growing IT infrastructure innovation needs.</p>
			<p>You have a unique advantage to partner with Asia’s largest <a href="https://uptimeinstitute.com/uptime-institute-awards/list/datacenter/amaravati/818" target="_blank">Uptime Institute TIER IV Certified</a> Data Center organisation with an access to scale-at-will capacity and uncompromising quality. This gives you the opportunity to build in a strong colocation and hosting service line into your own solution stack. </p>
			<p>The true-blue and award-winning cloud fabric, Harbour1<sup>®</sup>, is a stable and highly scalable enterprise cloud platform @Pi<sup>®</sup>. The flexibility, Software Defined Network (SDN) and Storage delivered out of Harbour1<sup>®</sup>, makes it a strong proposition for you as a Partner to leverage.</p>
			<p>The unique proposition of self-service provisioning makes it a technology marvel to take it to your customers. </p>
			<!-- <ul class="list-inline hb-ourListContAni">
				<li>
					<div class="hb-patnTrackBox">
						<span class="hb-withoutHover">
						<img src="images/menu-icons/ecommerce_ico.png">
						</span>
						<span class="hb-withHover">
							<img src="images/menu-icons/cs_ico.png">
						</span>
						<p>Positioning Partner As The Leader Of The League</p>
					</div>
				</li>
				<li>
					<div class="hb-patnTrackBox">
						<span class="hb-withoutHover">
						<img src="images/menu-icons/ecommerce_ico.png">
						</span>
						<span class="hb-withHover">
							<img src="images/menu-icons/cs_ico.png">
						</span>
						<p>99.995% Datacenter-Level Uptime Is GUARANTEED</p>
					</div>
				</li>
				<li>
					<div class="hb-patnTrackBox">
						<span class="hb-withoutHover">
						<img src="images/menu-icons/ecommerce_ico.png">
						</span>
						<span class="hb-withHover">
							<img src="images/menu-icons/cs_ico.png">
						</span>
						<p>State-Of-The-Art Infrastructure</p>
					</div>
				</li>
				<li>
					<div class="hb-patnTrackBox">
						<span class="hb-withoutHover">
						<img src="images/menu-icons/ecommerce_ico.png">
						</span>
						<span class="hb-withHover">
							<img src="images/menu-icons/cs_ico.png">
						</span>
						<p>Modular Architecture Model</p>
					</div>
				</li>
				<li>
					<div class="hb-patnTrackBox">
						<span class="hb-withoutHover">
						<img src="images/menu-icons/ecommerce_ico.png">
						</span>
						<span class="hb-withHover">
							<img src="images/menu-icons/cs_ico.png">
						</span>
						<p>Scale-At-Will</p>
					</div>
				</li>
				<li>
					<div class="hb-patnTrackBox">
						<span class="hb-withoutHover">
						<img src="images/menu-icons/ecommerce_ico.png">
						</span>
						<span class="hb-withHover">
							<img src="images/menu-icons/cs_ico.png">
						</span>
						<p>Self Service</p>
					</div>
				</li>
				<li>
					<div class="hb-patnTrackBox">
						<span class="hb-withoutHover">
						<img src="images/menu-icons/ecommerce_ico.png">
						</span>
						<span class="hb-withHover">
							<img src="images/menu-icons/cs_ico.png">
						</span>
						<p>Self Service</p>
					</div>
				</li>


			</ul> -->
				<ul class="list-inline hb-ourListCont hb-fourC	">
				<li>
					<span>
						<img src="images/partners/b1_ico.png">
					</span>
					<p>Positioning Partner As bThe Leader Of The League</p>
				</li>
				<li>
					<span>
						<img src="images/partners/b2_ico.png">
					</span>
					<p>99.995% Datacenter-Level Uptime Is GUARANTEED</p>
				</li>
				<li>
					<span>
						<img src="images/partners/b3_ico.png">
					</span>
					<p>State-Of-The-Art <br>Infrastructure</p>
				</li>
				<li>
					<span>
						<img src="images/partners/b4_ico.png">
					</span>
					<p>Modular<br>Architecture Model</p>
				</li>
				

			</ul>
			<ul class="list-inline  hb-ourListCont hb-thirC" style="margin-top: 36px;">
				<li>
					<span>
						<img src="images/partners/b5_ico.png">
					</span>
					<p>Scale-At-Will</p>
				</li>
				<li>
					<span>
						<img src="images/partners/b6_ico.png">
					</span>
					<p>Self Service</p>
				</li>
				<li>
					<span>
						<img src="images/partners/b7_ico.png">
					</span>
					<p>Agile Solution</p>
				</li>
			</ul>
		</div>
	</div>
</section>


<section>
	<div class="container">
		<div class="hb-whatDoGet">
			<h3>What Do You Get As A Partner?</h3>
			<p>The Integration Partner Program allows our partners to work with us to offer an expanded solution stack out of their stable.</p>
			<p>Our flexible benefit stack supports and contributes to your Go-To-Market strategy.</p>
			<p>In all the phases across customer interaction, be it pre-sales, sales operations, sales management, branding air cover, or a combination of any of the stated, we deliver value and differentiation to our partners to generate business.</p>
		</div>
		<ul class="list-inline hb-etDoImg hb-fourC">
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="images/122.png"></span>
						<small class="hb-hoCont">The essence of Pi Partner Program lies in its approach around collaborative planning and integrated go to market strategy. It is desinged to deliver quantified results and customer experience, while achiving common business goals.</small>
					</p>
					<h3>Collaborative Planning</h3>
				</div>
			</li>
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="images/122.png"></span>
						<small class="hb-hoCont">The essence of Pi Partner Program lies in its approach around collaborative planning and integrated go to market strategy. It is desinged to deliver quantified results and customer experience, while achiving common business goals.</small>
					</p>
					<h3>Referral Bonus</h3>
				</div>
			</li>
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="images/122.png"></span>
						<small class="hb-hoCont">The essence of Pi Partner Program lies in its approach around collaborative planning and integrated go to market strategy. It is desinged to deliver quantified results and customer experience, while achiving common business goals.</small>
					</p>
					<h3>Virtual Alliance Team</h3>
				</div>
			</li>
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="images/122.png"></span>
						<small class="hb-hoCont">The essence of Pi Partner Program lies in its approach around collaborative planning and integrated go to market strategy. It is desinged to deliver quantified results and customer experience, while achiving common business goals.</small>
					</p>
					<h3>Free Sandbox Environment</h3>
				</div>
			</li>
		</ul>
		<ul class="list-inline hb-etDoImg hb-thirC">
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="images/122.png"></span>
						<small class="hb-hoCont">The essence of Pi Partner Program lies in its approach around collaborative planning and integrated go to market strategy. It is desinged to deliver quantified results and customer experience, while achiving common business goals.</small>
					</p>
					<h3>Training & Workshop</h3>
				</div>
			</li>
			<li>
				<div class="hb-helBox">
					<p>
						<span><img src="images/122.png"></span>
						<small class="hb-hoCont">The essence of Pi Partner Program lies in its approach around collaborative planning and integrated go to market strategy. It is desinged to deliver quantified results and customer experience, while achiving common business goals.</small>
					</p>
					<h3>Co-Partnered Industry Events</h3>
				</div>
			</li>
			<li>
				<div class="hb-helBox"		>
					<p>
						<span><img src="images/122.png"></span>
						<small class="hb-hoCont">The essence of Pi Partner Program lies in its approach around collaborative planning and integrated go to market strategy. It is desinged to deliver quantified results and customer experience, while achiving common business goals.</small>
					</p>
					<h3>Marketing Collateral</h3>
				</div>
			</li>	
		</ul>
	</div>
</section>

<section>
	<div class="container">
		<div class="hb-tecPartners">
			<h3>Technology Partners</h3>
			<ul class="list-inline hb-companys hb-fourC text-center">
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>

			</ul>
		</div>
	</div>
</section>
<section>
	<div class="container">
		<div class="hb-tecPartners">
			<h3>Business Partners</h3>
			<ul class="list-inline hb-companys hb-fourC text-center">
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>
				<li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li><li>
					<a href="#">
						<img src="images/c1.png">
					</a>
				</li>

			</ul>
		</div>
	</div>
</section>
<?php
	include_once('includes/footer.php');
?>