<?php

$body.='<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">';
$body.='<html xmlns="https://www.w3.org/1999/xhtml">';
$body.='<head>';
$body.='<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />';
$body.='<title>Pi DATACENTERS</title>';
$body.='</head>';
$body.='<body>';
$body.='<div style="width:600px; margin:0 auto;">';
$body.='<table width="100%" cellpadding="0" cellspacing="0" style="text-align:center">';
$body.='<tr height="150">';
$body.='<td align="center" colspan="2"><a href="javascript:void(0)"><img src="images/mail-logo.png" /></a></td>';
$body.='</tr>';
$body.='<tr height="77" bgcolor="#103150">';
$body.='<td colspan="2" style="font-size:22px; color:#fff; font-family:Arial, Helvetica, sans-serif">Hi Micheal! <br />';
$body.='<span style="font-size:16px; color:#fff;">Thank you for choosing Pi</span></td>';
$body.='</tr>';
$body.='<tr height="100">';
$body.='<td colspan="2" align="center" style="font-size:22px; color:#20641b; font-weight:bold; font-family:Arial, Helvetica, sans-serif">Your (Order ID: 12051849125)<br />';
$body.='<span style="font-size:16px; color:#989898; font-weight:normal;">Placed on Monday,  29 Feb, 20106</span></td>';
$body.='</tr>';
$body.='<tr height="80">';
$body.='<td colspan="2" align="left" style="font-family:Arial, Helvetica, sans-serif; font-size:14px;"><span style="font-size:18px; padding-bottom:15px;"></span> <span style="color:#979797"> michealandmadan@gmail.com <br />';
$body.='+91 9701234870<br />';
$body.='Plot No: 301, Devi Residency, Telcom Nagar<br />';
$body.='Hyderabad - 500084, Telangana</span></td>';
$body.='<td>&nbsp;</td>';
$body.='</tr>';
$body.='<tr height="1">';
$body.='<td colspan="2" bgcolor="#999999"></td>';
$body.='</tr>';
$body.='<tr height="45">';
$body.='<td colspan="2" align="left"><span style="font-size:18px; font-family:Arial, Helvetica, sans-serif"><strong>confirm-box</strong></span></td>';
$body.='</tr>';
$body.='<tr height="40">';
$body.='<td align="left" style="font-family:Arial, Helvetica, sans-serif; color:#979797; font-size:14px;">Total Price</td>';
$body.='<td align="right" style="font-size:15px; font-weight:bold; color:#103150; font-family:Arial, Helvetica, sans-serif">Rs: 40,400</td>';
$body.='</tr>';
$body.='<tr height="40">';
$body.='<td align="left" style="font-family:Arial, Helvetica, sans-serif; color:#979797; font-size:14px;">You Paid</td>';
$body.='<td align="right" style="font-size:15px; font-weight:bold; color:#103150; font-family:Arial, Helvetica, sans-serif">Rs: 40,400</td>';
$body.='</tr>';
$body.='<tr height="40">';
$body.='<td align="left" style="font-family:Arial, Helvetica, sans-serif; color:#979797; font-size:14px;">Card Number</td>';
$body.='<td align="right" style="font-size:15px; font-weight:bold; color:#000; font-family:Arial, Helvetica, sans-serif">4163-XXXXXXXX-0294';
$body.='</td>';
$body.='</tr>';
$body.='<tr height="1">';
$body.='<td colspan="2" bgcolor="#999999"></td>';
$body.='</tr>';
$body.='<tr height="45">';
$body.='<td align="left"><span style="font-size:18px; font-family:Arial, Helvetica, sans-serif"><strong>Product Details</strong></span></td>';
$body.='</tr>';
$body.='<tr height="45">';
$body.='<td align="left"><span style="font-size:20px; font-family:Arial, Helvetica, sans-serif; color:#20641b; font-weight:bold;">Elastic Storage</span></td>';
$body.='</tr>';
$body.='<tr height="40">';
$body.='<td align="left" style="font-family:Arial, Helvetica, sans-serif; color:#979797; font-size:14px;">Object Storage (Tier 1)</td>';
$body.='<td align="right" style="font-size:15px; font-weight:bold; color:#103150; font-family:Arial, Helvetica, sans-serif">24 Months</td>';
$body.='</tr>';
$body.='<tr height="40">';
$body.='<td align="left" style="font-family:Arial, Helvetica, sans-serif; color:#979797; font-size:14px;">Block Storage (Tier 1 SSD / Flash)</td>';
$body.='<td align="right" style="font-size:15px; font-weight:bold; color:#103150; font-family:Arial, Helvetica, sans-serif">24 Months</td>';
$body.='</tr>';
$body.='<tr height="1">';
$body.='<td colspan="2" bgcolor="#999999"></td>';
$body.='</tr>';
$body.='<tr height="70">';
$body.='<td align="center" colspan="2" style="font-size:15px; color:#262626; font-family:Arial, Helvetica, sans-serif; line-height:22px;">';
$body.='Your Order Saved.';
$body.='</td>';
$body.='</tr>';
$body.='<tr height="20">';
$body.='<td align="center" colspan="2" style="font-size:15px; color:#979797; font-family:Arial, Helvetica, sans-serif; line-height:22px;">';
$body.='Our team would reach out, to help you implement the solution! “';
$body.='</td>';
$body.='</tr>';
$body.='<tr height="50">';
$body.='<td colspan="2" align="center";><a href="https://pidatacenters.com/about-pi/contact/" target="_blank"><img src="images/contact-img.png" /></a></td>';
$body.='</tr>';
$body.='<tr height="50">';
$body.='<td colspan="2"></td>';
$body.='</tr>';
$body.='</table>';
$body.='</div>';
$body.='</body>';
$body.='</html>';
echo $body;